# Inputs
sensor_msgs/Image[] images
sensor_msgs/PointCloud2[] clouds
geometry_msgs/TransformStamped[] transforms # transforms the pointclouds into the toolpaths frame id

---

# outputs
geometry_msgs/PoseArray[] detected_regions 
bool succeeded
string err_msg